POST http://localhost:8080/api/contracts
Content-Type: application/json

{
  "name":"contract3",
  "contractType":1,
  "approxBeginDate":"2022-10-20T09:12:29",
  "approxEndDate":"2022-10-20T09:12:29",
  "beginDate":"2022-10-20T09:12:29",
  "endDate":"2022-10-20T09:12:29",
  "sum":6000.0
}

###

POST http://localhost:8080/api/contracts.xlsx
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2xvZ2luIiwiZXhwIjoxNjY4MDgyMzYzfQ.DW-7lWfUXCaAp_92kA5mDCeWNghCEyLXSyBQZibPfCw

{
  "beginDate": "2022-11-18",
  "endDate": "2022-11-22"
}

